"""
Setup Environment Variables for Code Intent Detection Service
============================================================

Creates .env file with credentials for Redis Cloud and PostgreSQL.

Usage:
    python setup_env.py
"""

import os
import getpass
from pathlib import Path

def setup_env_file():
    """Interactive setup for .env file."""
    print("=" * 70)
    print("Code Intent Detection Service - Environment Setup")
    print("=" * 70)
    print()
    
    env_file = Path(__file__).parent / ".env"
    env_example = Path(__file__).parent / ".env.example"
    
    # Check if .env already exists
    if env_file.exists():
        overwrite = input(f"⚠️  .env file already exists. Overwrite? (y/n): ").strip().lower()
        if overwrite != "y":
            print("❌ Setup cancelled")
            return False
    
    print("📝 Setting up .env file...")
    print()
    
    # Load template from .env.example if it exists
    template = ""
    if env_example.exists():
        template = env_example.read_text(encoding="utf-8")
    else:
        # Fallback template
        template = """# Code Intent Detection Service - Environment Configuration
DETECTION_FEEDBACK_REPOSITORY_TYPE=hybrid
DETECTION_ENABLE_FEEDBACK_COLLECTION=true
DETECTION_FEEDBACK_BUFFER_SIZE=10000

# Redis Cloud Configuration
REDIS_CLOUD_HOST=redis-19088.c305.ap-south-1-1.ec2.cloud.redislabs.com
REDIS_CLOUD_PORT=19088
REDIS_CLOUD_USERNAME=default
REDIS_CLOUD_PASSWORD=

# PostgreSQL Configuration
POSTGRES_CONNECTION_STRING=postgresql://hakgal:hakgal123@127.0.0.1:5172/hakgal
"""
    
    # Ask for Redis credentials
    print("🔴 Redis Cloud Configuration")
    print("-" * 70)
    redis_host = input("Redis Cloud Host [redis-19088.c305.ap-south-1-1.ec2.cloud.redislabs.com]: ").strip()
    if not redis_host:
        redis_host = "redis-19088.c305.ap-south-1-1.ec2.cloud.redislabs.com"
    
    redis_port = input("Redis Cloud Port [19088]: ").strip()
    if not redis_port:
        redis_port = "19088"
    
    redis_username = input("Redis Cloud Username [default]: ").strip()
    if not redis_username:
        redis_username = "default"
    
    redis_password = getpass.getpass("Redis Cloud Password (leave empty to skip): ").strip()
    
    # Ask for PostgreSQL credentials
    print()
    print("🐘 PostgreSQL Configuration")
    print("-" * 70)
    postgres_conn = input("PostgreSQL Connection String [postgresql://hakgal:hakgal123@127.0.0.1:5172/hakgal]: ").strip()
    if not postgres_conn:
        postgres_conn = "postgresql://hakgal:hakgal123@127.0.0.1:5172/hakgal"
    
    # Build .env content
    env_content = f"""# Code Intent Detection Service - Environment Configuration
# Generated by setup_env.py
# DO NOT COMMIT THIS FILE TO VERSION CONTROL

# ============================================================
# Feedback Repository Configuration
# ============================================================
DETECTION_FEEDBACK_REPOSITORY_TYPE=hybrid
DETECTION_ENABLE_FEEDBACK_COLLECTION=true
DETECTION_FEEDBACK_BUFFER_SIZE=10000

# ============================================================
# Redis Cloud Configuration
# ============================================================
REDIS_CLOUD_HOST={redis_host}
REDIS_CLOUD_PORT={redis_port}
REDIS_CLOUD_USERNAME={redis_username}
"""
    
    if redis_password:
        env_content += f"REDIS_CLOUD_PASSWORD={redis_password}\n"
    else:
        env_content += "# REDIS_CLOUD_PASSWORD=  # Set your Redis password here\n"
    
    env_content += f"""
# ============================================================
# PostgreSQL Configuration
# ============================================================
POSTGRES_CONNECTION_STRING={postgres_conn}
"""
    
    # Write .env file
    try:
        env_file.write_text(env_content, encoding="utf-8")
        print()
        print("✅ .env file created successfully!")
        print(f"   Location: {env_file}")
        print()
        
        # Show summary
        print("📊 Configuration Summary:")
        print(f"   Redis Host: {redis_host}")
        print(f"   Redis Port: {redis_port}")
        print(f"   Redis Username: {redis_username}")
        print(f"   Redis Password: {'✅ Set' if redis_password else '⚠️  Not set (will use Memory fallback)'}")
        print(f"   PostgreSQL: {postgres_conn[:50]}...")
        print()
        
        if not redis_password:
            print("⚠️  Note: Redis password not set. System will use Memory Repository as fallback.")
            print("   To enable Redis, edit .env and set REDIS_CLOUD_PASSWORD")
        
        return True
        
    except Exception as e:
        print(f"❌ Failed to create .env file: {e}")
        return False

if __name__ == "__main__":
    try:
        if setup_env_file():
            print("=" * 70)
            print("✅ Setup Complete!")
            print("=" * 70)
            print()
            print("Next steps:")
            print("1. Review the .env file if needed")
            print("2. Run: python scripts/test_feedback_integration.py")
            print("3. Start the service: python -m uvicorn api.main:app --reload")
        else:
            print("❌ Setup failed")
            exit(1)
    except KeyboardInterrupt:
        print("\n\n⚠️  Setup cancelled by user")
        exit(1)
    except Exception as e:
        print(f"\n\n❌ Setup failed: {e}")
        import traceback
        traceback.print_exc()
        exit(1)

