config:
  default: true
  MD013: false
  MD022: false
  MD024: false
  MD026: false
  MD031: false
  MD032: false
  MD033: false
  MD036: false
  MD041: false
  MD050: false
  MD034: true
  MD040: true
  MD012:
    maximum: 2
globs:
  - "**/*.md"
ignores:
  - "node_modules"

