# Ruff Configuration for LLM Security Firewall
# Note: pyproject.toml [tool.ruff.lint] syntax has loading issues in some versions
# Using dedicated ruff.toml for reliable CI/local consistency

line-length = 88

[lint]
# Ignored rules (with justification):
ignore = [
    "S101",  # assert in tests (pytest standard)
    "S105",  # hardcoded test passwords (safe fixtures)
    "E501",  # line length (handled by formatter)
    "S110",  # try-except-pass (defensive coding)
    "S112",  # try-except-continue (defensive coding)
    "E722",  # bare except (legacy code)
    "E402",  # imports after sys.path manipulation (script pattern)
    "F841",  # unused variables in tests (intentional placeholders)
    "E701",  # multiple statements on one line (compact test helpers)
    "S104",  # binding to all interfaces (examples only)
    "F601",  # duplicate dict keys (false positive in multilingual)
]
