# Ruff Configuration for LLM Security Firewall
# Creator: Joerg Bollwahn
# Date: 2025-10-30
#
# POLICY: FIX all errors, NO allowlist for convenience
#         Only exceptions: Intentional patterns (assert in tests, pseudo-random for non-crypto)

line-length = 88

[lint]
select = ["E", "F", "W", "I", "S"]
ignore = []

[lint.per-file-ignores]
# Tests: assert (S101) and pseudo-random (S311) intentional
"tests/**/*.py" = ["S101", "S311", "S603", "S607"]

# Benchmarks: pseudo-random (S311), insecure hash (S324), import after sys.path (E402)
"benchmarks/**/*.py" = ["S311", "E402"]
"benchmarks/generate_dataset.py" = ["S324"]

# Monitoring/Spatial: pseudo-random for non-crypto (canaries, challenge generation)
"src/llm_firewall/monitoring/canaries.py" = ["S311"]
"src/llm_firewall/spatial/generator.py" = ["S311"]

# Error handling: Intentional try-except patterns
"src/llm_firewall/persuasion/ac_trie.py" = ["S110"]
"src/llm_firewall/risk/risk_scorer.py" = ["S110"]
"src/llm_firewall/calibration/lodo.py" = ["S112"]

# CLI: Subprocess for command execution
"src/llm_firewall/cli.py" = ["S603", "S607"]
