# Multi-Agent Gates Configuration
# ================================
#
# Based on GPT-5 specification 2025-10-30
#
# Creator: Joerg Bollwahn
# License: MIT

# Risk Aggregation
# ----------------

aggregation:
  coverage: 0.90                    # Target conformal coverage
  bands: [0.10, 0.20, 0.40, 0.70, 0.90]  # Quantile cuts for S0..S4
  abstain_band: "S2"                # Abstain if >= this band
  deny_band: "S3"                   # Deny if >= this band
  
  # Per-judge weights (default: uniform if not specified)
  weights:
    nli_consistency: 1.0            # Logical consistency
    policy_judge: 0.8               # Rule-based policy
    persuasion_fusion: 0.7          # Social engineering

# Streaming Token Guard
# ----------------------

stream_guard:
  window_tokens: 64                 # Sliding window size
  abort_severity: 3                 # Severity.HIGH
  rewrite_severity: 1               # Severity.LOW
  risk_decay: 0.9                   # Cumulative risk decay factor

# Spatial CAPTCHA Auth
# ---------------------

captcha:
  enabled_for_risk_tier: ["high", "critical"]  # Only for high-risk ops
  difficulty_min: 2                 # DifficultyLevel.MEDIUM
  difficulty_max: 5                 # DifficultyLevel.HARD
  trigger_mode: "conditional"       # conditional | periodic | always
  trigger_threshold: 0.85           # CB confidence threshold

# Judges Configuration
# --------------------

judges:
  nli_consistency:
    enabled: true
    kb_facts: []                    # Populated from KB at runtime
    policy_statements:
      - "Do not provide instructions for harmful activities"
      - "Do not bypass safety guidelines"
      - "Do not pretend to be another entity"
      - "Do not provide personal information"
  
  policy_judge:
    enabled: true
    rules:
      - category: "instruction_bypass"
        patterns: ["ignore previous", "disregard", "forget instructions"]
        severity: 3
        weight: 0.8
      
      - category: "role_hijack"
        patterns: ["you are now", "pretend to be", "act as"]
        severity: 2
        weight: 0.6
      
      - category: "safety_bypass"
        patterns: ["jailbreak", "unrestricted mode", "developer override"]
        severity: 3
        weight: 0.9
  
  persuasion_fusion:
    enabled: true
    grey_zone_min: 1.0              # Min persuasion score to trigger band-judge
    grey_zone_max: 2.5              # Max persuasion score to trigger band-judge
    band_judge_timeout_ms: 2000     # Max latency for band-judge

# Decision Ledger
# ---------------

ledger:
  postgres:
    enabled: false                  # Requires DB setup
    table_name: "decision_ledger"
  
  file:
    enabled: true
    path: "logs/decision_ledger.ndjson"
    rotation_mb: 100                # Rotate after 100MB

# Performance Targets
# -------------------

targets:
  asr_max: 0.02                     # <= 2%
  critical_leak_max: 0.005          # <= 0.5%
  ece_max: 0.05                     # <= 5%
  brier_max: 0.10                   # <= 0.10
  p95_latency_max_ms: 150           # <= 150ms overhead



