# Spatial CAPTCHA Configuration
# ===============================
#
# Creator: Joerg Bollwahn
# Date: 2025-10-30

# Performance Profiles
# --------------------
# Choose one: fast, balanced, paranoid

profiles:
  fast:
    enabled: false
    description: "Minimal latency, no authentication challenges"
    spatial_captcha:
      enabled: false
    
  balanced:
    enabled: true
    description: "Production default - reasonable security with acceptable latency"
    spatial_captcha:
      enabled: true
      trigger_mode: "conditional"  # Only when CB confidence < threshold
      trigger_threshold: 0.85
      default_difficulty: "medium"
      time_budget_ms: 8000
      max_attempts: 3
    
  paranoid:
    enabled: false
    description: "Maximum security - regular challenges regardless of CB"
    spatial_captcha:
      enabled: true
      trigger_mode: "periodic"  # Every N requests
      trigger_frequency: 10  # Challenge every 10th request
      default_difficulty: "hard"
      time_budget_ms: 10000
      max_attempts: 2

# Spatial CAPTCHA Settings
# -------------------------

spatial_captcha:
  # Challenge generation
  generator:
    seed_source: "timestamp"  # timestamp | random | fixed
    fixed_seed: null  # If seed_source is 'fixed'
  
  # Rendering
  renderer:
    output_dir: "spatial_challenges"
    image_size:
      width: 800
      height: 600
    cleanup_interval_hours: 24
    backend: "auto"  # auto | pil | matplotlib | none
  
  # Difficulty levels
  difficulty:
    easy:
      object_count: 2
      rotation_angles: [90, 180, 270]
      occlusion: false
      target_human_pass_rate: 0.95
    
    medium:
      object_count: 3
      rotation_angles: [45, 90, 135, 180]
      occlusion: true
      target_human_pass_rate: 0.90
    
    hard:
      object_count_range: [5, 7]
      rotation_angle_range: [15, 345]
      occlusion: true
      target_human_pass_rate: 0.85
  
  # Verification
  verification:
    min_response_time_ms: 500  # Faster = suspicious
    max_response_time_ms: 30000  # Slower = timeout
    suspicious_confidence_penalty: 0.8  # Multiply confidence by this
  
  # Adaptive difficulty
  adaptive:
    enabled: true
    min_attempts_before_adapt: 3
    easy_promotion_threshold: 0.8  # If accuracy > 80%, try medium
    hard_demotion_threshold: 0.5  # If accuracy < 50%, drop to medium
  
  # Multi-modal fusion (with Cultural Biometrics)
  fusion:
    cb_weight: 0.6
    spatial_weight: 0.4
    combined_threshold: 0.9  # Threshold for is_human
  
  # Accessibility
  accessibility:
    fallback_enabled: true
    fallback_method: "human_review"  # human_review | alternative_challenge
    max_failures_before_fallback: 3

# Database
# --------

database:
  table_name: "spatial_challenges"
  profile_table_name: "spatial_user_profiles"
  retention_days: 90  # Delete old challenges after N days

# Monitoring
# ----------

monitoring:
  enabled: true
  log_all_challenges: true
  log_suspicious_responses: true
  alert_on_high_failure_rate: true
  failure_rate_threshold: 0.5  # Alert if user fails > 50%
  alert_on_bot_pattern: true
  bot_pattern_threshold: 0.3  # Alert if confidence < 30%

# Integration
# -----------

integration:
  ocr_optical_memory:
    enabled: true
    store_challenges: true
    ocr_mode: "base"
  
  cultural_biometrics:
    enabled: true
    trigger_spatial_on_low_cb: true
    cb_threshold: 0.85

# Performance Targets (from paper)
# ---------------------------------

targets:
  human_pass_rate: 0.90  # >= 90%
  mllm_pass_rate: 0.31   # <= 31% (SOTA ceiling)
  false_positive_rate: 0.05  # <= 5%
  latency_p95_ms: 10000  # 95th percentile response time



