name: External Benign FPR (Stratified)

on:
  workflow_dispatch: {}
  schedule:
    - cron: "17 3 * * *"   # daily at 03:17 UTC

jobs:
  eval-fpr-stratified:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install project + tools
        run: |
          python -m pip install --upgrade pip
          # Install project
          python -m pip install -e .
          # Optional dependency for enrichment (guarded in code)
          python -m pip install langid || true

      - name: Sanity check - tools presence
        run: |
          test -f tools/enrich_external_benign.py
          test -f tools/eval_external_benign_fpr.py
          test -f tools/ci_gate_external_fpr.py
          test -f Makefile

      - name: Prepare external_benign corpus
        run: |
          # Expecting repo to provide external_benign/{indexes,samples}/...
          # If pulled from artifacts or dataset repo, add fetch step here
          test -d external_benign || { echo "external_benign/ missing"; exit 2; }
          test -f external_benign/indexes/metadata.csv || { echo "metadata.csv missing"; exit 2; }

      - name: Enrich + Evaluate + Gate
        run: |
          make ci-external \
            PYTHON=python \
            ROOT=external_benign \
            INCSV=external_benign/indexes/metadata.csv \
            OUTCSV=external_benign/indexes/metadata_enriched.csv \
            FPROUT=external_benign/indexes/fpr_external_stratified.json \
            UPPER_CODEFENCE=0.015 \
            UPPER_PURE=0.020 \
            MIN_N_PER_CLASS=300

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: external-benign-fpr-${{ github.run_id }}
          path: |
            external_benign/indexes/metadata_enriched.csv
            external_benign/indexes/fpr_external_stratified.json
          if-no-files-found: error

